# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: isaks
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  httpApi:
    id: ny2wtm2guh
    name: cms-api

functions:
  # Project functions
  fetchProjects:
    handler: handlers/project/fetchProjects.handler
    role:
      Fn::GetAtt:
        - DynamoDbAccessRole
        - Arn
    events:
      - httpApi:
          path: /project/fetch
          method: get

  createProject:
    handler: handlers/project/createProject.handler
    role:
      Fn::GetAtt:
        - DynamoDbAccessRole
        - Arn
    events:
      - httpApi:
          path: /project/create
          method: post

  deleteProject:
    handler: handlers/project/deleteProject.handler
    role:
      Fn::GetAtt:
        - DynamoDbAccessRole
        - Arn
    events:
      - httpApi:
          path: /project/{id}
          method: delete

  # User functions
  signup:
    handler: handlers/user/signup.handler
    role:
      Fn::GetAtt:
        - DynamoDbAccessRole
        - Arn
    events:
      - httpApi:
          path: /user/signup
          method: post

  signin:
    handler: handlers/user/signin.handler
    role:
      Fn::GetAtt:
        - DynamoDbAccessRole
        - Arn
    events:
      - httpApi:
          path: /user/signin
          method: post

resources:
  Resources:
    # DynamoDB Table
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    # DynamoDB Access Role
    DynamoDbAccessRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: sts:AssumeRole
              Principal:
                Service: lambda.amazonaws.com
        Policies:
          - PolicyName: DynamoDbAccessPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow # Add DynamoDB permissions
                  Action:
                    - dynamodb:PutItem
                    - dynamodb:GetItem
                    - dynamodb:UpdateItem
                    - dynamodb:DeleteItem
                  Resource: arn:aws:dynamodb:eu-north-1:586794470362:table/usersTable

                - Effect: Allow # Add CloudWatch permissions
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: arn:aws:logs:eu-north-1:*:*

                - Effect: Allow # Add VPC permissions for Lambda to interact with ElastiCache
                  Action:
                    - ec2:CreateNetworkInterface
                    - ec2:DescribeNetworkInterfaces
                    - ec2:DeleteNetworkInterface
                  Resource: "*"

                - Effect: Allow # Add ElastiCache permissions
                  Action:
                    - elasticache:DescribeCacheClusters
                    - elasticache:Connect
                  Resource: arn:aws:elasticache:eu-north-1:586794470362:serverlesscache:cms-cache
