# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: isaks
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  httpApi:
    id: ny2wtm2guh
    name: cms-api

functions:
  # Project functions
  fetchProjects:
    handler: handlers/project/fetchProjects.handler
    role:
      Fn::GetAtt:
        - DynamoDbAccessRole
        - Arn
    events:
      - httpApi:
          path: /project/fetch
          method: get

  createProject:
    handler: handlers/project/createProject.handler
    role:
      Fn::GetAtt:
        - DynamoDbAccessRole
        - Arn
    events:
      - httpApi:
          path: /project/create
          method: post

  deleteProject:
    handler: handlers/project/deleteProject.handler
    role:
      Fn::GetAtt:
        - DynamoDbAccessRole
        - Arn
    events:
      - httpApi:
          path: /project/{id}
          method: delete

  # User functions
  signup:
    handler: handlers/user/signup.handler
    role:
      Fn::GetAtt:
        - SignupRole
        - Arn
    events:
      - httpApi:
          path: /user/signup
          method: post

  signin:
    handler: handlers/user/signin.handler
    role:
      Fn::GetAtt:
        - DynamoDbAccessRole
        - Arn
    events:
      - httpApi:
          path: /user/signin
          method: post

  logout:
    handler: handlers/user/logout.handler
    role:
      Fn::GetAtt:
        - CloudWatchRole
        - Arn
    events:
      - httpApi:
          path: /user/logout
          method: post

  setRefreshToken:
    handler: handlers/user/setRefreshToken.handler
    role:
      Fn::GetAtt:
        - CloudWatchRole
        - Arn
    events:
      - httpApi:
          path: /user/setRefreshToken
          method: post

  refreshToken:
    handler: handlers/user/refreshToken.handler
    role:
      Fn::GetAtt:
        - CognitoAccessRole
        - Arn
    events:
      - httpApi:
          path: /user/refreshToken
          method: post

resources:
  Resources:
    # DynamoDB Table
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    # DynamoDB Access Role
    DynamoDbAccessRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: sts:AssumeRole
              Principal:
                Service: lambda.amazonaws.com
        Policies:
          - PolicyName: DynamoDbAccessPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow # DynamoDB permissions
                  Action:
                    - dynamodb:PutItem
                    - dynamodb:GetItem
                    - dynamodb:UpdateItem
                    - dynamodb:DeleteItem
                  Resource: arn:aws:dynamodb:eu-north-1:586794470362:table/usersTable

                - Effect: Allow # CloudWatch permissions
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: arn:aws:logs:eu-north-1:*:*

                - Effect: Allow # Cognito permissions (Add this to allow Lambda to interact with Cognito)
                  Action:
                    - cognito-idp:ListUsers
                    - cognito-idp:List
                    - cognito-idp:AdminGet
                    - cognito-idp:AdminList
                  Resource: arn:aws:cognito-idp:eu-north-1:586794470362:userpool/eu-north-1_EqPhIcyJw

    # Cognito and DynamoDB Access Role for signup
    SignupRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: sts:AssumeRole
              Principal:
                Service: lambda.amazonaws.com
        Policies:
          - PolicyName: SignupAccessPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - cognito-idp:SignUp
                    - cognito-idp:ListUsers
                  Resource: arn:aws:cognito-idp:eu-north-1:586794470362:userpool/eu-north-1_EqPhIcyJw
                - Effect: Allow
                  Action:
                    - dynamodb:PutItem
                    - dynamodb:GetItem
                    - dynamodb:UpdateItem
                    - dynamodb:DeleteItem
                  Resource: arn:aws:dynamodb:eu-north-1:586794470362:table/usersTable
                # CloudWatch Logs permissions
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: arn:aws:logs:eu-north-1:586794470362:log-group:/aws/lambda/*

    # Cognito Access Role
    CognitoAccessRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: sts:AssumeRole
              Principal:
                Service: lambda.amazonaws.com
        Policies:
          - PolicyName: CognitoAccessPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - cognito-idp:SignUp
                    - cognito-idp:ListUsers
                    - cognito-idp:InitiateAuth
                  Resource: arn:aws:cognito-idp:eu-north-1:586794470362:userpool/eu-north-1_EqPhIcyJw
                # CloudWatch Logs permissions
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: arn:aws:logs:eu-north-1:*:*

    # Simple cloudwatch role
    CloudWatchRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: sts:AssumeRole
              Principal:
                Service: lambda.amazonaws.com
        Policies:
          - PolicyName: CloudWatchPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: arn:aws:logs:eu-north-1:*:*
